[project]
name = "excelprocessor"
version = "0.1.0"
description = "Excel processor I made for myself "
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["openpyxl==3.1.5", "pandas==2.2.3"]
